apiVersion: apps/v1
kind: Deployment
metadata:
  name: secops-testbed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secops-testbed
  template:
    metadata:
      labels:
        app: secops-testbed
    spec:
      containers:
        - name: secops-testbed
          image: angelrita/base-ubuntu:latest
          command: ["/bin/bash", "-c", "sleep infinity"]
          stdin: true
          tty: true
